export const MOCK_REPORTS = [
  {
    id: '1',
    name: 'aaaaaa',
    description: 'aaaaaa',
    type: 'Performance',
    reportType: 'Custom',
    schedule: false,
    favorite: false,
  },
  {
    id: '2',
    name: 'ABC_Kotak_Raw_Value',
    description: '',
    type: 'Performance',
    reportType: 'Custom',
    schedule: false,
    favorite: false,
  },
  {
    id: '3',
    name: 'abcd',
    description: '',
    type: 'Availability Flap Summ...',
    reportType: 'Custom',
    schedule: false,
    favorite: false,
  },
  {
    id: '4',
    name: 'Active Alerts',
    description: 'Active Alerts',
    type: 'Active Alerts',
    reportType: 'Default',
    schedule: false,
    favorite: true,
  },
  {
    id: '5',
    name: 'Alert flap report',
    description: '',
    type: 'Metric Alerts',
    reportType: 'Custom',
    schedule: false,
    favorite: false,
  },
  {
    id: '6',
    name: 'All Access Point Availability - Last Month',
    description: 'All Access Point Availability - Last Month',
    type: 'Availability',
    reportType: 'Default',
    schedule: false,
    favorite: false,
  },
  {
    id: '7',
    name: 'All Access Point Availability - This Month',
    description: 'All Access Point Availability - This Month',
    type: 'Availability',
    reportType: 'Default',
    schedule: false,
    favorite: false,
  },
  {
    id: '8',
    name: 'All Access Point Availability - This Week',
    description: 'All Access Point Availability - This Week',
    type: 'Availability',
    reportType: 'Default',
    schedule: false,
    favorite: false,
  },
  {
    id: '9',
    name: 'All Devices System CPU Percentage - (Excluded Holidays) -...',
    description: 'All Devices System CPU Percentage - (Excluded Holidays) - ...',
    type: 'Custom Script',
    reportType: 'Default',
    schedule: false,
    favorite: false,
  },
  {
    id: '10',
    name: 'All Down Interfaces - Current',
    description: 'All Down Interfaces - Current',
    type: 'Active Alerts',
    reportType: 'Default',
    schedule: false,
    favorite: false,
  },
  {
    id: '11',
    name: 'All Down Monitors',
    description: 'All Down Monitors',
    type: 'Active Alerts',
    reportType: 'Default',
    schedule: false,
    favorite: false,
  },
  {
    id: '12',
    name: 'All Interface Availability - Last Day',
    description: 'All Interface Availability - Last Day',
    type: 'Availability',
    reportType: 'Default',
    schedule: false,
    favorite: false,
  },
  {
    id: '13',
    name: 'All Interface Availability - Last Week',
    description: 'All Interface Availability - Last Week',
    type: 'Availability',
    reportType: 'Default',
    schedule: false,
    favorite: false,
  },
  {
    id: '14',
    name: 'All Monitor Availability - Last Day',
    description: 'All Monitor Availability - Last Day',
    type: 'Availability',
    reportType: 'Default',
    schedule: false,
    favorite: false,
  },
  {
    id: '15',
    name: 'All Monitor Availability - Last Month',
    description: 'All Monitor Availability - Last Month',
    type: 'Availability',
    reportType: 'Default',
    schedule: false,
    favorite: false,
  },
  {
    id: '16',
    name: 'All Monitor Availability - Last Quarter',
    description: 'All Monitor Availability - Last Quarter',
    type: 'Availability',
    reportType: 'Default',
    schedule: false,
    favorite: false,
  },
];

export const REPORTS_PAGINATION_TOTAL = 2811;
