export const generateTrend = (baseValue, count = 20) => {
  return Array.from({ length: count }, (_, i) => {
    const random = (Math.random() - 0.5) * baseValue * 0.1;
    const sine = Math.sin(i / 3) * baseValue * 0.05;
    return Math.max(0, baseValue + random + sine);
  });
};

export const APM_SERVICES = [
  {
    id: 'notification-core-service',
    name: 'notification-core-service',
    type: 'service',
    icon: 'mdi:web',
    responseTime: 659.8,
    responseTimeTrend: generateTrend(659.8),
    throughput: 112,
    throughputTrend: generateTrend(112),
    errorCount: 5834,
    errorTrend: generateTrend(5834),
    status: 'critical',
    language: 'java',
  },
  {
    id: 'postgresql-db',
    name: 'postgresql-db',
    type: 'database',
    icon: 'mdi:database',
    responseTime: 1.2,
    responseTimeTrend: generateTrend(1.2),
    throughput: 105,
    throughputTrend: generateTrend(105),
    errorCount: 88,
    errorTrend: generateTrend(88),
    status: 'warning',
    language: 'postgresql',
  },
  {
    id: 'ft-database-server',
    name: 'ft-database-server',
    type: 'database',
    icon: 'mdi:database',
    responseTime: 0.5,
    responseTimeTrend: generateTrend(0.5),
    throughput: 119,
    throughputTrend: generateTrend(119),
    errorCount: 68,
    errorTrend: generateTrend(68),
    status: 'healthy',
    language: 'mongodb',
  },
  {
    id: 'ft-analytics-server',
    name: 'ft-analytics-server',
    type: 'service',
    icon: 'mdi:chart-line',
    responseTime: 1.23,
    responseTimeTrend: generateTrend(1.23),
    throughput: 112,
    throughputTrend: generateTrend(112),
    errorCount: 72,
    errorTrend: generateTrend(72),
    status: 'healthy',
    language: 'nodejs',
  },
  {
    id: 'ecommerce-app',
    name: 'ecommerce-app',
    type: 'service',
    icon: 'mdi:cart',
    responseTime: 1.38,
    responseTimeTrend: generateTrend(1.38),
    throughput: 126,
    throughputTrend: generateTrend(126),
    errorCount: 70,
    errorTrend: generateTrend(70),
    status: 'healthy',
    language: 'java',
  },
  {
    id: 'spring-boot-app',
    name: 'spring-boot-app',
    type: 'service',
    icon: 'mdi:leaf',
    responseTime: 1.24,
    responseTimeTrend: generateTrend(1.24),
    throughput: 120,
    throughputTrend: generateTrend(120),
    errorCount: 76,
    errorTrend: generateTrend(76),
    status: 'healthy',
    language: 'java',
  },
  {
    id: '13_60_ftmainserver',
    name: '13_60_ftmainserver',
    type: 'service',
    icon: 'mdi:server',
    responseTime: 2109,
    responseTimeTrend: generateTrend(2109),
    throughput: 1064,
    throughputTrend: generateTrend(1064),
    errorCount: 4285,
    errorTrend: generateTrend(4285),
    status: 'critical',
    language: 'java',
  },
  {
    id: 'ftmainserver',
    name: 'ftmainserver',
    type: 'service',
    icon: 'mdi:server',
    responseTime: 1951,
    responseTimeTrend: generateTrend(1951),
    throughput: 2104,
    throughputTrend: generateTrend(2104),
    errorCount: 5783,
    errorTrend: generateTrend(5783),
    status: 'critical',
    language: 'java',
  },
  {
    id: '12_203_ftmainserver',
    name: '12_203_ftmainserver',
    type: 'service',
    icon: 'mdi:server',
    responseTime: 271686,
    responseTimeTrend: generateTrend(271686),
    throughput: 7638,
    throughputTrend: generateTrend(7638),
    errorCount: 1350,
    errorTrend: generateTrend(1350),
    status: 'warning',
    language: 'java',
  },
];

export const TRACE_DATA = [
  {
    id: '1',
    serviceName: 'hibernatewithmysql',
    timestamp: 'Mon, Oct 13, 2025 05:03:29 PM',
    duration: 7742,
    resource: 'GET /products',
    spans: 5,
    status: 200,
  },
  {
    id: '2',
    serviceName: 'ProductCatalog_dotnet',
    timestamp: 'Mon, Oct 13, 2025 05:03:21 PM',
    duration: 4149,
    resource: 'GET api/products/{id}',
    spans: 3,
    status: 200,
  },
  {
    id: '3',
    serviceName: 'A',
    timestamp: 'Mon, Oct 13, 2025 05:03:48 PM',
    duration: 758761,
    resource: 'GET /serviceA',
    spans: 2,
    status: 200,
  },
  {
    id: '4',
    serviceName: 'D',
    timestamp: 'Mon, Oct 13, 2025 05:03:09 PM',
    duration: 431504,
    resource: 'GET /serviceD',
    spans: 6,
    status: 200,
  },
  {
    id: '5',
    serviceName: 'hibernatewithmysql',
    timestamp: 'Mon, Oct 13, 2025 05:03:47 PM',
    duration: 12206,
    resource: 'DELETE /delete/{id}',
    spans: 4,
    status: 500,
  },
];

export const SIDEBAR_ITEMS = [
  { id: 'services', label: 'Services', icon: 'mdi:application' },
  { id: 'explorer', label: 'Explorer', icon: 'mdi:compass' },
  { id: 'analytics', label: 'Analytics', icon: 'mdi:chart-line' },
];

export const EXPLORER_TRACE_METRICS = {
  count: 15420,
  countTrend: [12000, 12500, 13200, 13800, 14200, 14800, 15100, 15420],
  avgDuration: 1250,
  durationTrend: [1100, 1150, 1200, 1180, 1220, 1240, 1260, 1250],
  errors: 127,
  errorTrend: [95, 102, 110, 115, 120, 125, 128, 127],
};

export const ANALYTICS_PERFORMANCE_DATA = {
  requestRate: [8500, 8800, 9200, 9500, 9800, 10200, 10500, 10800],
  responseTime: [850, 820, 880, 900, 870, 890, 910, 895],
  errorRate: [2.5, 2.3, 2.8, 3.1, 2.9, 2.7, 2.6, 2.4],
};

export const ANALYTICS_DISTRIBUTION_DATA = {
  responseTime: [
    { label: '<100ms', value: 1250 },
    { label: '100-500ms', value: 3800 },
    { label: '500ms-1s', value: 2100 },
    { label: '1s-2s', value: 850 },
    { label: '>2s', value: 320 },
  ],
  requests: [
    { label: 'GET', value: 5200 },
    { label: 'POST', value: 2100 },
    { label: 'PUT', value: 850 },
    { label: 'DELETE', value: 420 },
    { label: 'PATCH', value: 180 },
  ],
  errors: [
    { label: '4xx', value: 180 },
    { label: '5xx', value: 95 },
    { label: 'Timeout', value: 42 },
    { label: 'Network', value: 28 },
    { label: 'Other', value: 15 },
  ],
};

export const ANALYTICS_TOP_SERVICES = [
  {
    name: 'notification-core-service',
    type: 'service',
    requests: 125420,
    avgLatency: 659,
    errorRate: 4.2,
    throughput: 112,
  },
  {
    name: 'postgresql-db',
    type: 'database',
    requests: 98750,
    avgLatency: 1.2,
    errorRate: 0.8,
    throughput: 105,
  },
  {
    name: 'ft-database-server',
    type: 'database',
    requests: 87320,
    avgLatency: 0.5,
    errorRate: 0.6,
    throughput: 119,
  },
  {
    name: 'ft-analytics-server',
    type: 'service',
    requests: 76540,
    avgLatency: 1.23,
    errorRate: 0.9,
    throughput: 112,
  },
  {
    name: 'ecommerce-app',
    type: 'service',
    requests: 65890,
    avgLatency: 1.38,
    errorRate: 1.1,
    throughput: 126,
  },
];

export const FILTER_SIDEBAR_CONFIG = [
  {
    key: 'search',
    type: 'search',
  },
  {
    key: 'status',
    type: 'select',
    label: 'Status',
    options: [
      { value: '', label: 'All' },
      { value: 'healthy', label: 'Healthy' },
      { value: 'warning', label: 'Warning' },
      { value: 'critical', label: 'Critical' },
    ],
    placeholder: 'Select status',
  },
  {
    key: 'language',
    type: 'select',
    label: 'Language',
    options: [
      { value: '', label: 'All' },
      { value: 'java', label: 'Java' },
      { value: 'nodejs', label: 'Node.js' },
      { value: 'python', label: 'Python' },
      { value: 'dotnet', label: '.NET' },
    ],
    placeholder: 'Select language',
  },
  {
    key: 'type',
    type: 'select',
    label: 'Type',
    options: [
      { value: '', label: 'All' },
      { value: 'service', label: 'Service' },
      { value: 'database', label: 'Database' },
    ],
    placeholder: 'Select type',
  },
];
