export const CATEGORY_CONFIGS = {
  'Server & Apps': {
    icon: 'mdi:server',
    color: 'var(--color-chart-cyan)',
    detailColumns: [
      'MONITOR',
      'STATUS',
      'IP',
      'TYPE',
      'CPU',
      'MEMORY',
      'DISK',
      'GROUP',
      'TAGS',
      'ACTIVE ALERTS',
      'APPS',
    ],
    dashboardWidgets: [
      'Health Overview',
      'Monitor Health By Severity',
      'CPU Usage Trend',
      'Memory Distribution',
    ],
  },
  Network: {
    icon: 'mdi:lan',
    color: 'var(--color-chart-blue)',
    detailColumns: [
      'DEVICE',
      'STATUS',
      'IP',
      'TYPE',
      'UPTIME',
      'BANDWIDTH IN',
      'BANDWIDTH OUT',
      'PACKET LOSS',
      'LATENCY',
    ],
    dashboardWidgets: [
      'Network Health',
      'Bandwidth Usage',
      'Top Talkers',
      'Interface Status',
    ],
  },
  SDN: {
    icon: 'mdi:network',
    color: 'var(--color-chart-violet)',
    detailColumns: [
      'CONTROLLER',
      'STATUS',
      'IP',
      'VERSION',
      'SWITCHES',
      'FLOWS',
      'TOPOLOGY',
    ],
    dashboardWidgets: [
      'SDN Overview',
      'Controller Health',
      'Flow Statistics',
      'Switch Distribution',
    ],
  },
  Cloud: {
    icon: 'mdi:cloud',
    color: 'var(--color-chart-green)',
    detailColumns: [
      'INSTANCE',
      'STATUS',
      'PROVIDER',
      'REGION',
      'TYPE',
      'CPU',
      'MEMORY',
      'STORAGE',
      'COST',
    ],
    dashboardWidgets: [
      'Cloud Resources',
      'Cost Analysis',
      'Performance Metrics',
      'Regional Distribution',
    ],
  },
  'Service Check': {
    icon: 'mdi:check-circle',
    color: 'var(--color-warning)',
    detailColumns: [
      'SERVICE',
      'STATUS',
      'URL/IP',
      'RESPONSE TIME',
      'LAST CHECK',
      'UPTIME',
      'SSL EXPIRY',
    ],
    dashboardWidgets: [
      'Service Availability',
      'Response Time Trend',
      'SSL Certificates',
      'Uptime Summary',
    ],
  },
  Virtualization: {
    icon: 'mdi:server-network',
    color: 'var(--color-chart-pink)',
    detailColumns: [
      'VM NAME',
      'STATUS',
      'HOST',
      'CPU',
      'MEMORY',
      'DISK',
      'NETWORK',
      'UPTIME',
    ],
    dashboardWidgets: [
      'VM Health',
      'Resource Utilization',
      'Host Distribution',
      'Performance Metrics',
    ],
  },
  HCI: {
    icon: 'mdi:database-cluster',
    color: 'var(--color-chart-teal)',
    detailColumns: [
      'CLUSTER',
      'STATUS',
      'NODES',
      'CPU',
      'MEMORY',
      'STORAGE',
      'IOPS',
      'THROUGHPUT',
    ],
    dashboardWidgets: [
      'Cluster Health',
      'Storage Performance',
      'Node Distribution',
      'Resource Trends',
    ],
  },
  Storage: {
    icon: 'mdi:harddisk',
    color: 'var(--color-chart-orange)',
    detailColumns: [
      'STORAGE',
      'STATUS',
      'TYPE',
      'CAPACITY',
      'USED',
      'FREE',
      'IOPS',
      'LATENCY',
    ],
    dashboardWidgets: [
      'Storage Overview',
      'Capacity Trend',
      'Performance Metrics',
      'Top Volumes',
    ],
  },
  'Container Orchestration': {
    icon: 'mdi:kubernetes',
    color: 'var(--color-chart-indigo)',
    detailColumns: [
      'CLUSTER',
      'STATUS',
      'NODES',
      'PODS',
      'SERVICES',
      'CPU',
      'MEMORY',
      'NAMESPACE',
    ],
    dashboardWidgets: [
      'Cluster Health',
      'Pod Distribution',
      'Resource Usage',
      'Service Status',
    ],
  },
  Service: {
    icon: 'mdi:cog',
    color: 'var(--color-chart-purple)',
    detailColumns: [
      'SERVICE',
      'STATUS',
      'HOST',
      'PORT',
      'PROTOCOL',
      'UPTIME',
      'CONNECTIONS',
    ],
    dashboardWidgets: [
      'Service Status',
      'Connection Trends',
      'Port Usage',
      'Protocol Distribution',
    ],
  },
  Process: {
    icon: 'mdi:application',
    color: 'var(--color-chart-green-alt)',
    detailColumns: [
      'PROCESS',
      'STATUS',
      'HOST',
      'PID',
      'CPU',
      'MEMORY',
      'THREADS',
      'UPTIME',
    ],
    dashboardWidgets: [
      'Process Health',
      'Resource Usage',
      'Top Processes',
      'Thread Analysis',
    ],
  },
  Container: {
    icon: 'mdi:docker',
    color: 'var(--color-chart-sky)',
    detailColumns: [
      'CONTAINER',
      'STATUS',
      'IMAGE',
      'HOST',
      'CPU',
      'MEMORY',
      'NETWORK',
      'UPTIME',
    ],
    dashboardWidgets: [
      'Container Health',
      'Resource Metrics',
      'Image Distribution',
      'Network Traffic',
    ],
  },
  Interface: {
    icon: 'mdi:ethernet',
    color: 'var(--color-chart-lime)',
    detailColumns: [
      'INTERFACE',
      'STATUS',
      'DEVICE',
      'SPEED',
      'IN TRAFFIC',
      'OUT TRAFFIC',
      'ERRORS',
      'DISCARDS',
    ],
    dashboardWidgets: [
      'Interface Status',
      'Traffic Analysis',
      'Error Rates',
      'Top Interfaces',
    ],
  },
  'WAN Link': {
    icon: 'mdi:wan',
    color: 'var(--color-chart-fuchsia)',
    detailColumns: [
      'LINK',
      'STATUS',
      'SOURCE',
      'DESTINATION',
      'BANDWIDTH',
      'UTILIZATION',
      'LATENCY',
      'JITTER',
    ],
    dashboardWidgets: [
      'Link Health',
      'Bandwidth Usage',
      'Latency Trends',
      'Quality Metrics',
    ],
  },
  Other: {
    icon: 'mdi:dots-horizontal',
    color: 'var(--color-chart-slate)',
    detailColumns: ['NAME', 'STATUS', 'TYPE', 'DESCRIPTION', 'LAST UPDATED'],
    dashboardWidgets: [
      'Overview',
      'Status Summary',
      'Recent Changes',
      'Alerts',
    ],
  },
};

export const NETWORK_DETAIL_TABS = [
  'Overview',
  'Interface',
  'Metric Explorer',
  'Configured Policies',
  'Active Policies',
];
