export const CATEGORY_CONFIGS = {
  'Server & Apps': {
    icon: 'mdi:server',
    color: 'var(--color-chart-cyan)',
    detailColumns: [
      'MONITOR',
      'STATUS',
      'IP',
      'TYPE',
      'CPU',
      'MEMORY',
      'DISK',
      'GROUP',
      'TAGS',
      'ACTIVE ALERTS',
      'APPS',
    ],
    dashboardWidgets: [
      'Health Overview',
      'Monitor Health By Severity',
      'CPU Usage Trend',
      'Memory Distribution',
    ],
  },
  CCTV: {
    icon: 'mdi:cctv',
    color: 'var(--color-chart-yellow)',
    detailColumns: [
      'DEVICE',
      'STATUS',
      'IP',
      'MODEL',
      'RESOLUTION',
      'UPTIME',
      'BANDWIDTH IN',
      'BANDWIDTH OUT',
    ],
    dashboardWidgets: [
      'CCTV Health',
      'Bandwidth Usage',
      'Alerts',
    ],
  },
  Network: {
    icon: 'mdi:lan',
    color: 'var(--color-chart-blue)',
    detailColumns: [
      'DEVICE',
      'STATUS',
      'IP',
      'TYPE',
      'UPTIME',
      'BANDWIDTH IN',
      'BANDWIDTH OUT',
      'PACKET LOSS',
      'LATENCY',
    ],
    dashboardWidgets: [
      'Network Health',
      'Bandwidth Usage',
      'Top Talkers',
      'Interface Status',
    ],
  },
  UPS: {
    icon: 'mdi:battery-charging',
    color: 'var(--color-chart-orange)',
    detailColumns: [
      'DEVICE',
      'STATUS',
      'IP',
      'MODEL',
      'BATTERY STATUS',
      'INPUT VOLTAGE',
      'OUTPUT LOAD',
      'TEMPERATURE',
      'UPTIME',
    ],
    dashboardWidgets: [
      'UPS Health',
      'Battery Capacity Trend',
      'Load Distribution',
      'Alerts',
    ],
  },
  /*
  SDN: {
    icon: 'mdi:network',
    color: 'var(--color-chart-violet)',
    detailColumns: [
      'CONTROLLER',
      'STATUS',
      'IP',
      'VERSION',
      'SWITCHES',
      'FLOWS',
      'TOPOLOGY',
    ],
    dashboardWidgets: [
      'SDN Overview',
      'Controller Health',
      'Flow Statistics',
      'Switch Distribution',
    ],
  },
  Cloud: {
    icon: 'mdi:cloud',
    color: 'var(--color-chart-green)',
    ...
  },
  'Service Check': { ... },
  Virtualization: { ... },
  HCI: { ... },
  Storage: { ... },
  'Container Orchestration': { ... },
  Service: { ... },
  Process: { ... },
  Container: { ... },
  Interface: { ... },
  'WAN Link': { ... },
  Other: { ... },
  */
};

export const NETWORK_DETAIL_TABS = ['Overview', 'Interface'];
