export const CATEGORY_CONFIGS = {
    'Server & Apps': {
        icon: 'mdi:server',
        color: '#06b6d4',
        detailColumns: [
            'MONITOR',
            'STATUS',
            'IP',
            'TYPE',
            'CPU',
            'MEMORY',
            'DISK',
            'GROUP',
            'TAGS',
            'ACTIVE ALERTS',
            'APPS',
        ],
        dashboardWidgets: [
            'Health Overview',
            'Monitor Health By Severity',
            'CPU Usage Trend',
            'Memory Distribution',
        ],
    },
    Network: {
        icon: 'mdi:lan',
        color: '#3b82f6',
        detailColumns: [
            'DEVICE',
            'STATUS',
            'IP',
            'TYPE',
            'UPTIME',
            'BANDWIDTH IN',
            'BANDWIDTH OUT',
            'PACKET LOSS',
            'LATENCY',
        ],
        dashboardWidgets: [
            'Network Health',
            'Bandwidth Usage',
            'Top Talkers',
            'Interface Status',
        ],
    },
    SDN: {
        icon: 'mdi:network',
        color: '#8b5cf6',
        detailColumns: [
            'CONTROLLER',
            'STATUS',
            'IP',
            'VERSION',
            'SWITCHES',
            'FLOWS',
            'TOPOLOGY',
        ],
        dashboardWidgets: [
            'SDN Overview',
            'Controller Health',
            'Flow Statistics',
            'Switch Distribution',
        ],
    },
    Cloud: {
        icon: 'mdi:cloud',
        color: '#10b981',
        detailColumns: [
            'INSTANCE',
            'STATUS',
            'PROVIDER',
            'REGION',
            'TYPE',
            'CPU',
            'MEMORY',
            'STORAGE',
            'COST',
        ],
        dashboardWidgets: [
            'Cloud Resources',
            'Cost Analysis',
            'Performance Metrics',
            'Regional Distribution',
        ],
    },
    'Service Check': {
        icon: 'mdi:check-circle',
        color: '#f59e0b',
        detailColumns: [
            'SERVICE',
            'STATUS',
            'URL/IP',
            'RESPONSE TIME',
            'LAST CHECK',
            'UPTIME',
            'SSL EXPIRY',
        ],
        dashboardWidgets: [
            'Service Availability',
            'Response Time Trend',
            'SSL Certificates',
            'Uptime Summary',
        ],
    },
    Virtualization: {
        icon: 'mdi:server-network',
        color: '#ec4899',
        detailColumns: [
            'VM NAME',
            'STATUS',
            'HOST',
            'CPU',
            'MEMORY',
            'DISK',
            'NETWORK',
            'UPTIME',
        ],
        dashboardWidgets: [
            'VM Health',
            'Resource Utilization',
            'Host Distribution',
            'Performance Metrics',
        ],
    },
    HCI: {
        icon: 'mdi:database-cluster',
        color: '#14b8a6',
        detailColumns: [
            'CLUSTER',
            'STATUS',
            'NODES',
            'CPU',
            'MEMORY',
            'STORAGE',
            'IOPS',
            'THROUGHPUT',
        ],
        dashboardWidgets: [
            'Cluster Health',
            'Storage Performance',
            'Node Distribution',
            'Resource Trends',
        ],
    },
    Storage: {
        icon: 'mdi:harddisk',
        color: '#f97316',
        detailColumns: [
            'STORAGE',
            'STATUS',
            'TYPE',
            'CAPACITY',
            'USED',
            'FREE',
            'IOPS',
            'LATENCY',
        ],
        dashboardWidgets: [
            'Storage Overview',
            'Capacity Trend',
            'Performance Metrics',
            'Top Volumes',
        ],
    },
    'Container Orchestration': {
        icon: 'mdi:kubernetes',
        color: '#6366f1',
        detailColumns: [
            'CLUSTER',
            'STATUS',
            'NODES',
            'PODS',
            'SERVICES',
            'CPU',
            'MEMORY',
            'NAMESPACE',
        ],
        dashboardWidgets: [
            'Cluster Health',
            'Pod Distribution',
            'Resource Usage',
            'Service Status',
        ],
    },
    Service: {
        icon: 'mdi:cog',
        color: '#a855f7',
        detailColumns: [
            'SERVICE',
            'STATUS',
            'HOST',
            'PORT',
            'PROTOCOL',
            'UPTIME',
            'CONNECTIONS',
        ],
        dashboardWidgets: [
            'Service Status',
            'Connection Trends',
            'Port Usage',
            'Protocol Distribution',
        ],
    },
    Process: {
        icon: 'mdi:application',
        color: '#22c55e',
        detailColumns: [
            'PROCESS',
            'STATUS',
            'HOST',
            'PID',
            'CPU',
            'MEMORY',
            'THREADS',
            'UPTIME',
        ],
        dashboardWidgets: [
            'Process Health',
            'Resource Usage',
            'Top Processes',
            'Thread Analysis',
        ],
    },
    Container: {
        icon: 'mdi:docker',
        color: '#0ea5e9',
        detailColumns: [
            'CONTAINER',
            'STATUS',
            'IMAGE',
            'HOST',
            'CPU',
            'MEMORY',
            'NETWORK',
            'UPTIME',
        ],
        dashboardWidgets: [
            'Container Health',
            'Resource Metrics',
            'Image Distribution',
            'Network Traffic',
        ],
    },
    Interface: {
        icon: 'mdi:ethernet',
        color: '#84cc16',
        detailColumns: [
            'INTERFACE',
            'STATUS',
            'DEVICE',
            'SPEED',
            'IN TRAFFIC',
            'OUT TRAFFIC',
            'ERRORS',
            'DISCARDS',
        ],
        dashboardWidgets: [
            'Interface Status',
            'Traffic Analysis',
            'Error Rates',
            'Top Interfaces',
        ],
    },
    'WAN Link': {
        icon: 'mdi:wan',
        color: '#d946ef',
        detailColumns: [
            'LINK',
            'STATUS',
            'SOURCE',
            'DESTINATION',
            'BANDWIDTH',
            'UTILIZATION',
            'LATENCY',
            'JITTER',
        ],
        dashboardWidgets: [
            'Link Health',
            'Bandwidth Usage',
            'Latency Trends',
            'Quality Metrics',
        ],
    },
    Other: {
        icon: 'mdi:dots-horizontal',
        color: '#64748b',
        detailColumns: ['NAME', 'STATUS', 'TYPE', 'DESCRIPTION', 'LAST UPDATED'],
        dashboardWidgets: [
            'Overview',
            'Status Summary',
            'Recent Changes',
            'Alerts',
        ],
    },
};
