export const MOCK_SLOS = [
  {
    id: '1',
    name: 'Monitor-SLO-Weekly-Perf-Windows',
    status: 'Ok',
    sloType: 'Performance',
    frequency: 'Daily',
    target: '90%',
    achieved: '100%',
    violation: '0%',
    errorBudgetLeft: '2 h 24 m',
    mttr: '-',
    mtbf: '-',
  },
  {
    id: '2',
    name: 'slo-tag-coorelation',
    status: 'Ok',
    sloType: 'Availability',
    frequency: 'Quarterly',
    target: '75%',
    achieved: '93.56%',
    violation: '6.44%',
    errorBudgetLeft: '2 W 2 d 18 h 55 m 17 s',
    mttr: '5 d 19 h 4 m 43 s',
    mtbf: 'N/A',
  },
  {
    id: '3',
    name: 'slo-monthly-interface',
    status: 'Warning',
    sloType: 'Availability',
    frequency: 'Monthly',
    target: '75%',
    achieved: '80.68%',
    violation: '19.32%',
    errorBudgetLeft: '1 d 18 h 55 m 17 s',
    mttr: '5 d 19 h 4 m 43 s',
    mtbf: 'N/A',
  },
  {
    id: '4',
    name: 'Monitor-SLO-Monthly-Ava-Server,Network,W...',
    status: 'Breached',
    sloType: 'Availability',
    frequency: 'Monthly',
    target: '90%',
    achieved: '80.68%',
    violation: '19.32%',
    errorBudgetLeft: '2 d 19 h 4 m 43 s',
    mttr: '5 d 19 h 4 m 43 s',
    mtbf: 'N/A',
  },
  {
    id: '5',
    name: 'Interface-SLO-Weekly-Ava-Network',
    status: 'Breached',
    sloType: 'Availability',
    frequency: 'Weekly',
    target: '90%',
    achieved: '16.92%',
    violation: '83.08%',
    errorBudgetLeft: '-5 d 2 h 46 m 43 s',
    mttr: '5 d 19 h 34 m 43 s',
    mtbf: 'N/A',
  },
];
