import { Icon } from '@iconify/react';
import { useState } from 'react';
import styles from './trap-list.module.css';

const MOCK_TRAPS = [
  {
    id: '1',
    name: 'clogMessageGenerated',
    trapOid: '1.3.6.1.4.1.9.9.41.2.0.1',
    source: '172.16.9.221',
    severity: 'critical',
    count: 1704,
    message: 'When a syslog message is generated by the device, this notification is sent. The notification includes the facility, severity, and message text.',
    timestamp: 'Thu, Apr 17, 2025 12:20:46 PM',
    acknowledged: true,
    facility: 'System',
    mnemonic: 'CONFIG_I',
  },
  {
    id: '2',
    name: 'ciscoConfigManEvent',
    trapOid: '1.3.6.1.4.1.9.9.43.2.0.1',
    source: '172.16.9.221',
    severity: 'warning',
    count: 36,
    message: 'Notification of a configuration management event as recorded in ccmHistoryEventTable.',
    timestamp: 'Thu, Apr 17, 2025 11:57:55 AM',
    acknowledged: false,
    facility: 'Config',
    mnemonic: 'SYS_RELOAD',
  },
  {
    id: '3',
    name: 'linkDown',
    trapOid: '1.3.6.1.6.3.1.1.5.3',
    source: '192.168.1.5',
    severity: 'major',
    count: 12,
    message: 'A linkDown trap signifies that the SNMP entity, acting in an agent role, has detected that the ifOperStatus object for one of its communication links is about to enter the down state.',
    timestamp: 'Thu, Apr 17, 2025 10:30:15 AM',
    acknowledged: false,
    interface: 'GigabitEthernet0/1',
    status: 'Down',
  },
  {
    id: '4',
    name: 'coldStart',
    trapOid: '1.3.6.1.6.3.1.1.5.1',
    source: '10.0.0.5',
    severity: 'info',
    count: 1,
    message: 'A coldStart trap signifies that the SNMP entity, acting in an agent role, is reinitializing itself such that its configuration may be altered.',
    timestamp: 'Thu, Apr 17, 2025 09:15:00 AM',
    acknowledged: true,
    reason: 'Power Cycle',
  },
  {
    id: '5',
    name: 'authenticationFailure',
    trapOid: '1.3.6.1.6.3.1.1.5.5',
    source: '172.16.9.225',
    severity: 'minor',
    count: 8,
    message: 'An authenticationFailure trap signifies that the SNMP entity has received a protocol message that is not properly authenticated.',
    timestamp: 'Thu, Apr 17, 2025 08:45:22 AM',
    acknowledged: false,
    attemptedUser: 'admin_test',
  },
];

const SEVERITY_CONFIG = {
  critical: { color: '#ef4444', icon: 'mdi:alert-circle', label: 'Critical' },
  major: { color: '#f97316', icon: 'mdi:alert', label: 'Major' },
  minor: { color: '#eab308', icon: 'mdi:alert-outline', label: 'Minor' },
  warning: { color: '#3b82f6', icon: 'mdi:alert-octagon', label: 'Warning' },
  info: { color: '#10b981', icon: 'mdi:information', label: 'Info' },
};

const TrapRow = ({ trap, isExpanded, onToggle, isSelected, onSelect, onViewHistory }) => {
  const config = SEVERITY_CONFIG[trap.severity] || SEVERITY_CONFIG.info;

  return (
    <div className={styles.accordionRow} data-expanded={isExpanded}>
      <div className={styles.rowMain} onClick={onToggle}>
        <div className={styles.rowSelect} onClick={(e) => e.stopPropagation()}>
          <input 
            type="checkbox" 
            checked={isSelected} 
            onChange={() => onSelect(trap.id)}
            className={styles.rowCheckbox}
          />
        </div>

        {/* Column 1: Identity */}
        <div className={styles.rowIdentity}>
          <div 
            className={styles.rowIcon} 
            style={{ color: isExpanded ? '#fff' : config.color, background: isExpanded ? config.color : 'rgba(255,255,255,0.03)' }}
          >
            <Icon icon={config.icon} width={18} height={18} />
          </div>
          <div className={styles.rowInfo}>
            <span className={styles.rowName}>{trap.name}</span>
            <span className={styles.rowSub}>
              <Icon icon="mdi:qrcode-scan" width={10} /> {trap.trapOid}
            </span>
          </div>
        </div>

        {/* Column 2: Source */}
        <div className={styles.columnSource}>
          <div className={styles.sourceText}>
            <Icon icon="mdi:ip-network" width={14} />
            {trap.source}
          </div>
        </div>

        {/* Column 3: Stats (Count) */}
        <div className={styles.columnStats}>
          <span className={styles.countLabel}>Occurrences</span>
          <span className={styles.countValue}>{trap.count}</span>
        </div>

        {/* Column 4: Time */}
        <div className={styles.columnTime}>
             <span className={styles.timeLabel}>Last Seen</span>
             <span className={styles.timeValue}>{trap.timestamp.split(' ').slice(0, 3).join(' ')}</span>
             <span className={styles.rowSub}>{trap.timestamp.split(' ').slice(3).join(' ')}</span>
        </div>

        {/* Column 5: Status */}
        <div className={styles.rowStatus}>
          <span className={`${styles.statusBadge} ${trap.acknowledged ? styles.statusAck : styles.statusNew}`}>
            {trap.acknowledged ? 'Acknowledged' : 'New Trap'}
          </span>
        </div>

        {/* Column 6: Action */}
        <div className={styles.rowAction}>
          <button 
            className={styles.historyBtn}
            onClick={(e) => {
              e.stopPropagation();
              onViewHistory && onViewHistory(trap);
            }}
            title="View Full History & Logs"
          >
            <Icon icon="mdi:history" width={18} height={18} />
          </button>
          <div className={styles.chevron}>
            <Icon icon="mdi:chevron-down" width={18} height={18} />
          </div>
        </div>
      </div>

      {isExpanded && (
        <div className={styles.rowDetails}>
          <div className={styles.detailsContentWrapper}>
             
             {/* Section 1: Message Payload */}
             <div className={styles.detailSection}>
                <h4 className={styles.sectionTitle}>
                   <Icon icon="mdi:text-box-search-outline" /> 
                   Trap Content Payload
                </h4>
                <div className={styles.messageBoxWrapper}>
                   <div className={styles.messageHeader}>
                      <span className={styles.messageFormat}>Raw String</span>
                      <button className={styles.copyBtn} title="Copy Payload">
                         <Icon icon="mdi:content-copy" width={14} />
                      </button>
                   </div>
                   <div className={styles.messageBox}>
                      {trap.message}
                   </div>
                </div>
             </div>

             {/* Section 2: Technical Metadata */}
             <div className={styles.detailSection}>
                <h4 className={styles.sectionTitle}>
                   <Icon icon="mdi:cog-box" /> 
                   Technical Metadata
                </h4>
                <div className={styles.metadataGrid}>
                   <div className={styles.metaItem}>
                      <span className={styles.metaLabel}>Object Identifier (OID)</span>
                      <span className={styles.metaValue}>{trap.trapOid}</span>
                   </div>
                   <div className={styles.metaRow}>
                      <div className={styles.metaItem}>
                         <span className={styles.metaLabel}>Source Node</span>
                         <span className={styles.metaValue}>{trap.source}</span>
                      </div>
                      <div className={styles.metaItem}>
                         <span className={styles.metaLabel}>Occurrences</span>
                         <span className={styles.metaValue}>{trap.count}</span>
                      </div>
                   </div>
                   <div className={styles.metaRow}>
                      <div className={styles.metaItem}>
                         <span className={styles.metaLabel}>Facility</span>
                         <span className={styles.metaValue}>{trap.facility || 'Unknown'}</span>
                      </div>
                      <div className={styles.metaItem}>
                         <span className={styles.metaLabel}>Mnemonic</span>
                         <span className={styles.metaValue}>{trap.mnemonic || 'N/A'}</span>
                      </div>
                   </div>
                   {trap.interface && (
                      <div className={styles.metaItem}>
                        <span className={styles.metaLabel}>Active Interface</span>
                        <span className={styles.metaValue} style={{color: 'var(--color-accent-cyan)'}}>{trap.interface}</span>
                      </div>
                   )}
                </div>
             </div>

             {/* Section 3: Event Lifecycle */}
             <div className={styles.detailSection}>
                <h4 className={styles.sectionTitle}>
                   <Icon icon="mdi:calendar-clock" /> 
                   Incident Sequence
                </h4>
                <div className={styles.timeline}>
                   <div className={styles.timelineItem}>
                      <div className={styles.timelinePoint} style={{ background: config.color }} />
                      <div className={styles.timelineContent}>
                         <div className={styles.timelineHeader}>
                            <span className={styles.timelineLabel}>Root Event</span>
                            <span className={styles.timelineTime}>2h 15m ago</span>
                         </div>
                         <div className={styles.timelineSub}>Initial PDU received and decoded</div>
                      </div>
                   </div>
                   <div className={styles.timelineItem}>
                      <div className={styles.timelinePoint} />
                      <div className={styles.timelineContent}>
                         <div className={styles.timelineHeader}>
                            <span className={styles.timelineLabel}>State Update</span>
                            <span className={styles.timelineTime}>45m ago</span>
                         </div>
                         <div className={styles.timelineSub}>Count updated to {trap.count} events</div>
                      </div>
                   </div>
                </div>
             </div>

          </div>
        </div>
      )}
    </div>
  );
};

const TrapList = ({ searchQuery, onViewHistory }) => {
  const [expandedIds, setExpandedIds] = useState(new Set(['1']));
  const [selectedTraps, setSelectedTraps] = useState([]);

  const filteredTraps = MOCK_TRAPS.filter(
    (trap) =>
      trap.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      trap.trapOid.toLowerCase().includes(searchQuery.toLowerCase()) ||
      trap.source.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const toggleSelectAll = (e) => {
    if (e.target.checked) {
      setSelectedTraps(filteredTraps.map(t => t.id));
    } else {
      setSelectedTraps([]);
    }
  };

  const handleSelectTrap = (id) => {
    setSelectedTraps(prev => 
      prev.includes(id) ? prev.filter(tId => tId !== id) : [...prev, id]
    );
  };

  const toggleAccordion = (id) => {
    const next = new Set(expandedIds);
    if (next.has(id)) {
      next.delete(id);
    } else {
      next.add(id);
    }
    setExpandedIds(next);
  };

  return (
    <div className={styles.listContainer}>
      <div className={styles.tableHeaderRow}>
        <div className={styles.headerSelect}>
          <input 
            type="checkbox" 
            className={styles.rowCheckbox}
            checked={selectedTraps.length === filteredTraps.length && filteredTraps.length > 0} 
            onChange={toggleSelectAll}
          />
        </div>
        <span>Identity & Trap OID</span>
        <span>Source Node</span>
        <span>Stats</span>
        <span>Timestamp</span>
        <span>Status</span>
        <span></span>
      </div>

      <div className={styles.listBody}>
        {filteredTraps.map((trap) => (
          <TrapRow
            key={trap.id}
            trap={trap}
            isExpanded={expandedIds.has(trap.id)}
            onToggle={() => toggleAccordion(trap.id)}
            isSelected={selectedTraps.includes(trap.id)}
            onSelect={handleSelectTrap}
            onViewHistory={onViewHistory}
          />
        ))}
      </div>

      <div className={styles.pagination}>
        <div className={styles.paginationLeft}>
          <button className={styles.paginationBtn}>«</button>
          <button className={styles.paginationBtn}>‹</button>
          <button className={`${styles.paginationBtn} ${styles.paginationBtnActive}`}>1</button>
          <button className={styles.paginationBtn}>2</button>
          <button className={styles.paginationBtn}>›</button>
          <button className={styles.paginationBtn}>»</button>
        </div>
        <div className={styles.paginationRight}>
          <span className={styles.paginationCount}>
            Showing 1 - {filteredTraps.length} of {filteredTraps.length} Traps
          </span>
        </div>
      </div>
    </div>
  );
};

export default TrapList;
