export const MOCK_ALERTS = [
  {
    id: '1',
    alert: 'Interface Availability',
    type: 'Availability',
    monitor: 'ciscostack1.test.com',
    metric: 'interface.status',
    instance: 'Gi2/0/14-10814',
    incidentDetails: '',
    lastSeen: 'Mon, Jun 23, 2025 12:21:18 PM',
    value: 'Down',
    duration: '5 days 23 hours 39 minutes',
    severity: 'down',
    category: 'Network',
  },
  {
    id: '2',
    alert: 'Interface Availability',
    type: 'Availability',
    monitor: 'moxa-switch',
    metric: 'interface.status',
    instance: 'Ethernet Port Gi2-12',
    incidentDetails: '',
    lastSeen: 'Sun, Jun 22, 2025 03:01:18 PM',
    value: 'Down',
    duration: '5 days 23 hours 39 minutes',
    severity: 'down',
    category: 'Network',
  },
  {
    id: '3',
    alert: 'Availability',
    type: 'Availability',
    monitor: 'gF.g9.com',
    metric: 'status',
    instance: '',
    incidentDetails: 'INC0010065',
    lastSeen: 'Mon, Jun 23, 2025 12:30:18 PM',
    value: 'Down',
    duration: '5 days 23 hours 48 minutes',
    severity: 'down',
    category: 'Server',
  },
  {
    id: '4',
    alert: 'Interface Availability',
    type: 'Availability',
    monitor: 'ciscostack1.test.com',
    metric: 'interface.status',
    instance: 'Gi11/0/4-11104',
    incidentDetails: '',
    lastSeen: 'Mon, Jun 23, 2025 12:21:18 PM',
    value: 'Down',
    duration: '5 days 23 hours 39 minutes',
    severity: 'down',
    category: 'Network',
  },
  {
    id: '5',
    alert: 'Interface Availability',
    type: 'Availability',
    monitor: 'moxa-switch',
    metric: 'interface.status',
    instance: 'Ethernet Port Gi2-12',
    incidentDetails: '',
    lastSeen: 'Sun, Jun 22, 2025 03:01:18 PM',
    value: 'Unreachable',
    duration: '5 days 23 hours 39 minutes',
    severity: 'unreachable',
    category: 'Network',
  },
  {
    id: '6',
    alert: 'CPU Utilization',
    type: 'Performance',
    monitor: 'server-01',
    metric: 'cpu.percent',
    instance: 'eth4-4',
    incidentDetails: '',
    lastSeen: 'Sun, Jun 22, 2025 03:01:18 PM',
    value: 'Critical',
    duration: '2 hours 15 minutes',
    severity: 'critical',
    category: 'Server',
  },
  {
    id: '7',
    alert: 'Memory Usage',
    type: 'Performance',
    monitor: 'router-core-01',
    metric: 'memory.percent',
    instance: '',
    incidentDetails: '',
    lastSeen: 'Sun, Jun 22, 2025 03:01:18 PM',
    value: 'Warning',
    duration: '1 hour 30 minutes',
    severity: 'warning',
    category: 'Network',
  },
  {
    id: '8',
    alert: 'Interface Availability Correlation Policy',
    type: 'Availability',
    monitor: '192.168.2.4:1',
    metric: 'interface.status',
    instance: 'Et0/1-2',
    incidentDetails: '',
    lastSeen: 'Mon, Jun 23, 2025 12:21:18 PM',
    value: 'Down',
    duration: '2 minutes 40 seconds',
    severity: 'critical',
    category: 'Server',
    correlatedAlerts: 2,
  },
];
