// Mock network topology data with hierarchical structure and connections
export const MOCK_TOPOLOGY_DATA = {
  network: {
    name: 'Network',
    children: [
      {
        name: 'Router',
        type: 'group',
        children: [
          {
            name: 'Cisco Systems',
            type: 'vendor',
            children: [
              {
                id: 'router-1',
                name: 'HB1.hb1.com',
                ip: '172.16.9.221',
                type: 'router',
                status: 'online',
                vendor: 'Cisco',
                model: 'ISR 4451',
                connections: ['sw-1', 'sw-2', 'fw-1'],
              },
              {
                id: 'router-2',
                name: 'cisco841.snr-edatas.local',
                ip: '172.16.12.86',
                type: 'router',
                status: 'offline',
                vendor: 'Cisco',
                model: 'ISR 841',
                connections: ['sw-3'],
              },
              {
                id: 'router-3',
                name: 'Gandhinagar_RTU_ES1',
                ip: '192.168.1.1',
                type: 'router',
                status: 'offline',
                vendor: 'Cisco',
                model: 'ASR 1001',
                connections: ['router-4', 'sw-4'],
              },
              {
                id: 'router-4',
                name: 'PMG-Router.test.com',
                ip: '172.16.8.90',
                type: 'router',
                status: 'online',
                vendor: 'Cisco',
                model: 'ISR 4331',
                connections: ['router-1', 'router-3', 'fw-1'],
              },
            ],
          },
          {
            name: 'Hewlett Packard Enterprise',
            type: 'vendor',
            children: [
              {
                id: 'router-5',
                name: 'Router_231',
                ip: '192.168.231.2',
                type: 'router',
                status: 'offline',
                vendor: 'HPE',
                model: 'FlexNetwork',
                connections: ['sw-5'],
              },
              {
                id: 'router-6',
                name: 'Router___',
                ip: '192.168.241.2',
                type: 'router',
                status: 'online',
                vendor: 'HPE',
                model: 'MSR3000',
                connections: ['sw-6', 'ap-1'],
              },
            ],
          },
        ],
      },
      {
        name: 'Firewall',
        type: 'group',
        children: [
          {
            name: 'Fortinet',
            type: 'vendor',
            children: [
              {
                id: 'fw-1',
                name: 'fg_firewall.mindarrauy.com',
                ip: '172.16.8.111',
                type: 'firewall',
                status: 'online',
                vendor: 'Fortinet',
                model: 'FortiGate 100F',
                connections: ['router-1', 'router-4', 'srv-1', 'srv-2'],
              },
            ],
          },
        ],
      },
      {
        name: 'Switch',
        type: 'group',
        children: [
          {
            name: 'Cisco Systems',
            type: 'vendor',
            children: [
              {
                id: 'sw-1',
                name: 'ciscostack1.test.com',
                ip: '172.16.8.211',
                type: 'switch',
                status: 'offline',
                vendor: 'Cisco',
                model: 'Catalyst 3850',
                connections: ['router-1', 'ap-1', 'ap-2', 'srv-1'],
              },
              {
                id: 'sw-2',
                name: 'ciscostack2.test.com',
                ip: '172.16.8.212',
                type: 'switch',
                status: 'online',
                vendor: 'Cisco',
                model: 'Catalyst 2960',
                connections: ['router-1', 'ap-3', 'srv-2'],
              },
              {
                id: 'sw-3',
                name: 'Cisco Switch',
                ip: '172.16.9.202',
                type: 'switch',
                status: 'offline',
                vendor: 'Cisco',
                model: 'Catalyst 9300',
                connections: ['router-2', 'srv-3'],
              },
            ],
          },
          {
            name: 'D-Link',
            type: 'vendor',
            children: [
              {
                id: 'sw-4',
                name: 'Dlink',
                ip: '192.168.1.10',
                type: 'switch',
                status: 'online',
                vendor: 'D-Link',
                model: 'DGS-1210',
                connections: ['router-3', 'ap-4'],
              },
            ],
          },
          {
            name: 'Hewlett Packard Enterprise',
            type: 'vendor',
            children: [
              {
                id: 'sw-5',
                name: 'g4g4.com',
                ip: '172.16.8.225',
                type: 'switch',
                status: 'warning',
                vendor: 'HPE',
                model: 'Aruba 2930F',
                connections: ['router-5', 'srv-4'],
              },
              {
                id: 'sw-6',
                name: 'g3g3.com',
                ip: '172.16.8.224',
                type: 'switch',
                status: 'online',
                vendor: 'HPE',
                model: 'ProCurve 2810',
                connections: ['router-6', 'ap-5', 'srv-5'],
              },
            ],
          },
        ],
      },
      {
        name: 'Servers',
        type: 'group',
        children: [
          {
            name: 'Dell',
            type: 'vendor',
            children: [
              {
                id: 'srv-1',
                name: 'Web Server 1',
                ip: '192.168.10.1',
                type: 'server',
                status: 'online',
                vendor: 'Dell',
                model: 'PowerEdge R740',
                connections: ['fw-1', 'sw-1', 'srv-3'],
              },
              {
                id: 'srv-2',
                name: 'Web Server 2',
                ip: '192.168.10.2',
                type: 'server',
                status: 'online',
                vendor: 'Dell',
                model: 'PowerEdge R740',
                connections: ['fw-1', 'sw-2', 'srv-3'],
              },
              {
                id: 'srv-3',
                name: 'DB Server',
                ip: '192.168.10.3',
                type: 'server',
                status: 'online',
                vendor: 'Dell',
                model: 'PowerEdge R940',
                connections: ['sw-3', 'srv-1', 'srv-2'],
              },
            ],
          },
          {
            name: 'HP',
            type: 'vendor',
            children: [
              {
                id: 'srv-4',
                name: 'File Server',
                ip: '192.168.10.4',
                type: 'server',
                status: 'warning',
                vendor: 'HP',
                model: 'ProLiant DL380',
                connections: ['sw-5'],
              },
              {
                id: 'srv-5',
                name: 'Backup Server',
                ip: '192.168.10.5',
                type: 'server',
                status: 'offline',
                vendor: 'HP',
                model: 'ProLiant DL360',
                connections: ['sw-6'],
              },
            ],
          },
        ],
      },
      {
        name: 'Access Points',
        type: 'group',
        children: [
          {
            name: 'Cisco Meraki',
            type: 'vendor',
            children: [
              {
                id: 'ap-1',
                name: 'Lobby AP',
                ip: '10.0.0.1',
                type: 'access-point',
                status: 'online',
                vendor: 'Cisco',
                model: 'Meraki MR46',
                connections: ['sw-1', 'router-6'],
              },
              {
                id: 'ap-2',
                name: 'Conf Room AP',
                ip: '10.0.0.2',
                type: 'access-point',
                status: 'online',
                vendor: 'Cisco',
                model: 'Meraki MR46',
                connections: ['sw-1'],
              },
              {
                id: 'ap-3',
                name: 'Cafeteria AP',
                ip: '10.0.0.3',
                type: 'access-point',
                status: 'online',
                vendor: 'Cisco',
                model: 'Meraki MR56',
                connections: ['sw-2'],
              },
              {
                id: 'ap-4',
                name: 'Floor 1 AP',
                ip: '10.0.0.4',
                type: 'access-point',
                status: 'online',
                vendor: 'Cisco',
                model: 'Meraki MR46',
                connections: ['sw-4'],
              },
              {
                id: 'ap-5',
                name: 'Floor 2 AP',
                ip: '10.0.0.5',
                type: 'access-point',
                status: 'warning',
                vendor: 'Cisco',
                model: 'Meraki MR46',
                connections: ['sw-6'],
              },
            ],
          },
        ],
      },
    ],
  },
  sdn: {
    name: 'SDN',
    children: [
      {
        name: 'Cisco SD-WAN',
        type: 'group',
        children: [
          {
            id: 'sdn-1',
            name: 'Manager',
            type: 'controller',
            status: 'online',
            connections: ['sdn-2', 'sdn-3'],
          },
          {
            id: 'sdn-2',
            name: 'Manager Node',
            ip: '10.10.1.1',
            type: 'manager',
            status: 'online',
            connections: ['sdn-1', 'sdn-3'],
          },
          {
            id: 'sdn-3',
            name: 'WAN Edge',
            type: 'edge',
            status: 'online',
            connections: ['sdn-1', 'sdn-2'],
          },
        ],
      },
    ],
  },
  cloud: {
    name: 'Global',
    children: [
      {
        name: 'AWS Cloud',
        type: 'cloud-provider',
        children: [
          {
            id: 'cloud-1',
            name: 'us-east-1',
            type: 'region',
            status: 'online',
            connections: ['cloud-3', 'topic-1'],
          },
          {
            id: 'cloud-2',
            name: 'us-west-1',
            type: 'region',
            status: 'online',
            connections: ['cloud-3'],
          },
          {
            id: 'cloud-3',
            name: 'testdb(us-east-1)',
            type: 'database',
            status: 'online',
            connections: ['cloud-1', 'cloud-2', 'topic-2'],
          },
        ],
      },
      {
        name: 'MyTopic',
        type: 'service',
        children: [
          {
            id: 'topic-1',
            name: 'testlam(MyTopic)',
            type: 'topic',
            status: 'online',
            connections: ['cloud-1', 'topic-2'],
          },
          {
            id: 'topic-2',
            name: 'ServiceQueue',
            type: 'queue',
            status: 'warning',
            connections: ['cloud-3', 'topic-1'],
          },
        ],
      },
    ],
  },
};