export const TRAP_LIVE_STREAM_DATA = [
  {
    id: 1,
    time: '12:45:32 PM',
    source: '172.16.9.221',
    trapName: 'clogMessageGenerated',
    severity: 'info',
    message: 'When a syslog message is generated...',
    acknowledged: false,
  },
  {
    id: 2,
    time: '12:44:18 PM',
    source: '172.16.8.105',
    trapName: 'linkDown',
    severity: 'critical',
    message: 'Interface Gi0/1 changed state to down',
    acknowledged: false,
  },
  {
    id: 3,
    time: '12:43:05 PM',
    source: '172.16.9.221',
    trapName: 'ciscoConfigManEvent',
    severity: 'warning',
    message: 'Configuration management event detected',
    acknowledged: true,
  },
  {
    id: 4,
    time: '12:41:52 PM',
    source: '192.168.1.1',
    trapName: 'authenticationFailure',
    severity: 'major',
    message: 'SNMP authentication failure from 10.0.0.5',
    acknowledged: false,
  },
  {
    id: 5,
    time: '12:40:30 PM',
    source: '172.16.9.221',
    trapName: 'coldStart',
    severity: 'info',
    message: 'Device restarted (cold start)',
    acknowledged: true,
  },
];
